# Generated by Django 5.0.6 on 2024-08-21 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_basket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="size",
        ),
    ]
