# Generated by Django 5.0.6 on 2024-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_basket_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="size",
            field=models.CharField(default="XS", max_length=4),
        ),
    ]
