# Generated by Django 5.0.6 on 2024-08-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_basket_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="price",
            field=models.IntegerField(),
        ),
    ]
