# Generated by Django 5.0.6 on 2024-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_basket_quantity_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
