# Generated by Django 5.0.6 on 2024-08-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryproducts",
            name="code",
            field=models.CharField(default="empty", max_length=128),
        ),
    ]
